### PR TITLE
Don't throw the "empty heading" error when the element uses ng-bind or ng-bind-html

### PR DESCRIPTION
**Pull request by ChrisMBarr**
A fix for Issue #11! :tada:

### CODE REVIEW

**Comment by ChrisMBarr** [comment]
Excellent, thanks!  Could you up the version number and release this to NPM?

**Comment by nikestep** [comment]
Unless I made a mistake, I have already done this. v0.1.8

**Comment by ChrisMBarr** [comment]
Oops, my bad!  I actually consume this though [this gulp plugin](https://github.com/ewu02/gulp-html-angular-validate) and i forgot for a moment.  I need to ask them consume this new version.

**Comment by nikestep** [comment]
I think if you do `npm update` you'll just get it.

**Pull request merged**
